module.exports = {
	After: 'After',
	StartTouching: 'StartTouching',
	StartInside: 'StartInside',
	InsideStartTouching: 'InsideStartTouching',
	EnclosingStartTouching: 'EnclosingStartTouching',
	Enclosing: 'Enclosing',
	EnclosingEndTouching: 'EnclosingEndTouching',
	ExactMatch: 'ExactMatch',
	Inside: 'Inside',
	InsideEndTouching: 'InsideEndTouching',
	EndInside: 'EndInside',
	EndTouching: 'EndTouching',
	Before: 'Before',
};
